# -*- coding: utf-8 -*-
"""CDA_asgmt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125CBkJABKyWShK6RRJdGUqa_RXdmHDv2

Problem 1

Problem statement: Consider the lung cancer data and solve the following questions using Python: Basic EDA Questions, Association & Crosstab, Statistical Testing, Correlation & Interpretation, Logistic Regression, Advanced Modeling, Model Evaluation, and a final Research Question summarizing the findings and public health implications.
"""

import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency, skew, norm
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.metrics import roc_curve, auc, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt

df = pd.read_csv('/content/sample_data/lung_disease01.csv')

print("--- Basic EDA ---")
# i) Age distribution
age_skew = skew(df['Age'])
print(f"Age Skewness: {age_skew:.3f}")
print("Age Describe:\n", df['Age'].describe())

# ii) Smokers vs Non-smokers
smoker_prop = df['Smoking'].value_counts(normalize=True)
print("\nSmoking Proportion:\n", smoker_prop)

# iii) Income group frequency
income_freq = df['Income'].value_counts()
print("\nIncome Frequency:\n", income_freq)

# iv) High pollution percentage
poll_prop = df['Pollution'].value_counts(normalize=True) * 100
print("\nPollution Percentage:\n", poll_prop)

# v) Lung disease prevalence
ld_prev = df['LungDisease'].value_counts(normalize=True) * 100
print("\nLung Disease Prevalence:\n", ld_prev)

print("\n--- Association & Crosstab ---")
ct_smoke_ld = pd.crosstab(df['Smoking'], df['LungDisease'])
print("\nContingency Table: Smoking vs Lung Disease\n", ct_smoke_ld)

ct_poll_ld = pd.crosstab(df['Pollution'], df['LungDisease'], normalize='index') * 100
print("\nContingency Table: Pollution vs Lung Disease (Row %)\n", ct_poll_ld)

ct_inc_ld = pd.crosstab(df['Income'], df['LungDisease'], normalize='index') * 100
print("\nContingency Table: Income vs Lung Disease (Row %)\n", ct_inc_ld)

print("\n--- Statistical Testing ---")
# Chi-square tests
chi2_smoke, p_smoke, _, _ = chi2_contingency(pd.crosstab(df['Smoking'], df['LungDisease']))
chi2_poll, p_poll, _, _ = chi2_contingency(pd.crosstab(df['Pollution'], df['LungDisease']))
print(f"Chi2 Smoking vs LD: p-value = {p_smoke:.5f}")
print(f"Chi2 Pollution vs LD: p-value = {p_poll:.5f}")

# Odds ratio for Smoking vs Lung Disease
# OR = (Smoker_Yes * NonSmoker_No) / (Smoker_No * NonSmoker_Yes)
a = ct_smoke_ld.loc['Yes', 'Yes']
b = ct_smoke_ld.loc['Yes', 'No']
c = ct_smoke_ld.loc['No', 'Yes']
d = ct_smoke_ld.loc['No', 'No']
or_smoke = (a * d) / (b * c)
print(f"Odds Ratio for Smoking: {or_smoke:.3f}")

print("\n--- Correlation ---")
df['LungDisease_num'] = df['LungDisease'].map({'Yes': 1, 'No': 0})
df['Smoking_num'] = df['Smoking'].map({'Yes': 1, 'No': 0})
df['Pollution_num'] = df['Pollution'].map({'High': 1, 'Low': 0})

corr_smoke_ld = df[['Smoking_num', 'LungDisease_num']].corr().iloc[0,1]
corr_age_ld = df[['Age', 'LungDisease_num']].corr().iloc[0,1]
print(f"Correlation (Smoking, Lung Disease): {corr_smoke_ld:.3f}")
print(f"Correlation (Age, Lung Disease): {corr_age_ld:.3f}")

print("\n--- Logistic Regression ---")
# Make sure we use proper reference categories.
model = smf.logit("LungDisease_num ~ C(Smoking, Treatment(reference='No')) + Age + C(Pollution, Treatment(reference='Low')) + C(Income, Treatment(reference='Low'))", data=df).fit(disp=0)
print(model.summary().tables[1])
params = model.params
conf = model.conf_int()
conf['OR'] = params
conf.columns = ['2.5%', '97.5%', 'OR']
print("\nOdds Ratios (Main Model):\n", np.exp(conf['OR']))

print("\n--- Advanced Modeling ---")
model_int = smf.logit("LungDisease_num ~ C(Smoking, Treatment(reference='No')) * C(Pollution, Treatment(reference='Low')) + Age + C(Income, Treatment(reference='Low'))", data=df).fit(disp=0)
print(model_int.summary().tables[1])

print("\n--- Model Evaluation (Main Model) ---")
preds = model.predict(df)
pred_class = (preds > 0.5).astype(int)

cm = confusion_matrix(df['LungDisease_num'], pred_class)
acc = accuracy_score(df['LungDisease_num'], pred_class)
tn, fp, fn, tp = cm.ravel()
sensitivity = tp / (tp + fn)
specificity = tn / (tn + fp)

print(f"Confusion Matrix:\n{cm}")
print(f"Accuracy: {acc:.3f}")
print(f"Sensitivity: {sensitivity:.3f}")
print(f"Specificity: {specificity:.3f}")

fpr, tpr, thresholds = roc_curve(df['LungDisease_num'], preds)
roc_auc = auc(fpr, tpr)
print(f"AUC: {roc_auc:.3f}")

plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc="lower right")
plt.savefig('roc_curve.png')

"""Here are the problems along with their respective Python solutions, presented one by one as requested.

### **Problem 2**

**Problem Statement:**
Suppose we want to determine if three different exercise programs impact weight loss differently. We recruit 90 people to participate in an experiment in which we randomly assign (using uniform distribution) 30 people to follow either program A, program B, or program C for one month. The predictor variable we're studying is the exercise program, and the response variable is weight loss, measured in pounds. Conduct a one-way ANOVA to determine if there is a statistically significant difference between the resulting weight loss from the three programs, check the model assumptions, and analyze treatment differences.

**Python Code:**
Since no dataset URL is provided for this problem, the code simulates the data based on the prompt's description before running the ANOVA, post-hoc tests, and plotting.
"""

import numpy as np
import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Simulate the data
np.random.seed(42)
data = pd.DataFrame({
    'Program': np.repeat(['A', 'B', 'C'], 30),
    'WeightLoss': np.concatenate([
        np.random.normal(loc=5, scale=1.5, size=30),  # Program A
        np.random.normal(loc=7, scale=2.0, size=30),  # Program B
        np.random.normal(loc=4, scale=1.8, size=30)   # Program C
    ])
})

group_A = data[data['Program'] == 'A']['WeightLoss']
group_B = data[data['Program'] == 'B']['WeightLoss']
group_C = data[data['Program'] == 'C']['WeightLoss']

# 2. Check Assumptions
# Levene's test for equal variances
stat, p_levene = stats.levene(group_A, group_B, group_C)
print(f"Levene's Test p-value: {p_levene:.3f} (If > 0.05, variances are equal)")

# 3. One-Way ANOVA Test
f_stat, p_val = stats.f_oneway(group_A, group_B, group_C)
print(f"\nANOVA F-statistic: {f_stat:.3f}, p-value: {p_val:.3f}")

# 4. Post-Hoc Test (Tukey's HSD) to analyze treatment differences
tukey = pairwise_tukeyhsd(endog=data['WeightLoss'], groups=data['Program'], alpha=0.05)
print("\nPost-Hoc Analysis:")
print(tukey)

# 5. Visualizations
fig, ax = plt.subplots(1, 2, figsize=(14, 5))

# Boxplot
sns.boxplot(x='Program', y='WeightLoss', data=data, palette='Set2', ax=ax[0])
ax[0].set_title('Weight Loss by Exercise Program')
ax[0].set_ylabel('Weight Loss (lbs)')

# Q-Q Plot for Normality check
sm.qqplot(data['WeightLoss'], line='s', ax=ax[1])
ax[1].set_title("Q-Q Plot of Data (Normality Check)")

plt.tight_layout()
plt.show()

"""---

### **Problem 3**

**Problem Statement:**
Consider the Anemia Levels in Nigeria dataset: (`[https://www.kaggle.com/datasets/adeolaadesina/factors-affecting-children-anemia-level/data](https://www.kaggle.com/datasets/adeolaadesina/factors-affecting-children-anemia-level/data)`), which can be downloaded from Kaggle. The dataset comes from the 2018 Nigeria Demographic and Health Surveys (NDHS). It explores the impact of mothers' age and socioeconomic factors on anemia levels among children aged 0-59 months across Nigeria's 36 states and the Federal Capital Territory. Based on the above data, create a contingency table, apply chi-square test, formulate hypothesis, create a contribution diagram, and interpret the findings.

**Python Code:**
*Note: Kaggle datasets cannot be directly fetched via URL without API authentication. The code below assumes you have downloaded the file as `anemia.csv` and uses a simulated contingency table structure for demonstration.*
"""

import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns

# Hypotheses formulation
print("H0: Socioeconomic factors (Wealth Index) and Anemia levels are independent.")
print("H1: Socioeconomic factors (Wealth Index) and Anemia levels are associated.\n")

# Normally, you would load data like this:
# df = pd.read_csv('anemia.csv')
# contingency_table = pd.crosstab(df['Wealth_Index'], df['Anemia_Level'])

# Creating a mock contingency table based on typical NDHS survey features
np.random.seed(42)
mock_data = pd.DataFrame({
    'Wealth_Index': np.random.choice(['Poor', 'Middle', 'Rich'], 500, p=[0.4, 0.4, 0.2]),
    'Anemia_Level': np.random.choice(['Severe', 'Moderate', 'Mild', 'Not Anemic'], 500)
})

# 1. Create Contingency Table
contingency_table = pd.crosstab(mock_data['Wealth_Index'], mock_data['Anemia_Level'])
print("Contingency Table:\n", contingency_table)

# 2. Apply Chi-Square Test
chi2, p, dof, expected = stats.chi2_contingency(contingency_table)
print(f"\nChi-Square Statistic: {chi2:.3f}")
print(f"p-value: {p:.3f}")

# Interpretation logic
if p < 0.05:
    print("Conclusion: Reject H0. There is a significant association between the variables.")
else:
    print("Conclusion: Fail to reject H0. No significant association found.")

# 3. Create Contribution Diagram (Heatmap of Standardized Residuals)
residuals = (contingency_table - expected) / np.sqrt(expected)

plt.figure(figsize=(8, 5))
sns.heatmap(residuals, annot=True, cmap="coolwarm", center=0)
plt.title('Chi-Square Standardized Residuals\n(Contribution Diagram)')
plt.ylabel('Wealth Index')
plt.xlabel('Anemia Level')
plt.show()

"""---

### **Problem 4**

**Problem Statement:**
Suppose, there are three drug treatments (drug A, drug B, and drug C) with the outcome of a disease or no disease. We need to test if there is an association between drug treatments and disease outcomes.
The following table:
Treatments | no disease | disease
drug A | 40 | 10
drug B | 10 | 40
drug C | 25 | 25
Perform Fisher's exact test for the above contingency table, post-hoc test for Fisher's exact test and interpret your findings.

**Python Code:**
A standard Fisher's Exact Test computationally handles 2x2 tables natively in `scipy`. For a larger table, we use a global Chi-Square test (or an R-like simulation if strictly required), and then perform 2x2 Fisher's Exact tests for the post-hoc pairwise comparisons with Bonferroni correction.
"""

import numpy as np
import scipy.stats as stats
import itertools

# 1. Define Contingency Table
table = np.array([[40, 10],   # Drug A
                  [10, 40],   # Drug B
                  [25, 25]])  # Drug C

drugs = ['Drug A', 'Drug B', 'Drug C']

# Global Test (Chi-Square) to check overall association
chi2, p_global, _, _ = stats.chi2_contingency(table)
print(f"Global Chi-Square p-value: {p_global:.5f}\n")

# 2. Post-Hoc Pairwise Fisher's Exact Tests
comparisons = list(itertools.combinations(range(3), 2))
p_values = []

print("Post-Hoc Pairwise Fisher's Exact Tests:")
for i, j in comparisons:
    sub_table = [table[i], table[j]]
    res = stats.fisher_exact(sub_table)
    p_values.append(res.pvalue)

# 3. Bonferroni Correction & Interpretation
alpha = 0.05
alpha_adj = alpha / len(comparisons)

for idx, (i, j) in enumerate(comparisons):
    sig = "Significant" if p_values[idx] < alpha_adj else "Not Significant"
    print(f"{drugs[i]} vs {drugs[j]} | p-value: {p_values[idx]:.5e} | {sig} (Adjusted Alpha: {alpha_adj:.3f})")

"""---

### **Problem 5**

**Problem Statement:**
A researcher is interested in how variables, such as GRE (Graduate Record Exam scores), GPA (grade point average) and prestige of the undergraduate institution, effect admission into graduate school. The response variable, admit/don't admit, is a binary variable. The data set taken from `[https://stats.idre.ucla.edu/stat/data/binary.csv](https://stats.idre.ucla.edu/stat/data/binary.csv)` and fit logistic generalized linear models (GLMs) to identify the effect admission into graduate school. Interpret the result.

**Python Code:**
"""

import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt

# 1. Read Data
url5 = "https://stats.idre.ucla.edu/stat/data/binary.csv"
df5 = pd.read_csv(url5)

# 2. Fit Logistic GLM
# admit predicted by gre, gpa, and rank (treated as categorical variable using C())
model5 = smf.logit("admit ~ gre + gpa + C(rank)", data=df5).fit()
print(model5.summary())

# 3. Plotting Effect (Probability of admission vs GPA, holding GRE mean and Rank at 2)
df_pred = pd.DataFrame({
    'gre': [df5['gre'].mean()] * 100,
    'gpa': np.linspace(df5['gpa'].min(), df5['gpa'].max(), 100),
    'rank': [2] * 100
})
df_pred['prob_admit'] = model5.predict(df_pred)

plt.figure(figsize=(8, 5))
plt.plot(df_pred['gpa'], df_pred['prob_admit'], color='indigo', linewidth=2)
plt.title('Predicted Probability of Admission by GPA\n(Holding Rank=2 and GRE=Mean)')
plt.xlabel('GPA')
plt.ylabel('Probability of Admission')
plt.grid(True, alpha=0.3)
plt.show()

"""---

### **Problem 6**

**Problem Statement:**
The number of awards earned by students at one high school. Predictors of the number of awards earned include the type of program in which the student was enrolled (e.g., vocational, general or academic) and the score their final exam in math. The data set is taken from `[https://stats.idre.ucla.edu/stat/data/poisson_sim.csv](https://stats.idre.ucla.edu/stat/data/poisson_sim.csv)` and fit the poisson generalized linear models (GLMs) to identify the factors associated with number of awards earned by students at one high school. Interpret the result.

**Python Code:**
"""

import pandas as pd
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Read Data
url6 = "https://stats.idre.ucla.edu/stat/data/poisson_sim.csv"
df6 = pd.read_csv(url6)

# 2. Fit Poisson GLM
# C(prog) treats the program type as categorical
model6 = smf.poisson("num_awards ~ math + C(prog)", data=df6).fit()
print(model6.summary())

# 3. Visualization
plt.figure(figsize=(8, 6))
sns.scatterplot(x="math", y="num_awards", hue="prog", data=df6, palette='viridis', alpha=0.7)
sns.lineplot(x="math", y=model6.predict(df6), hue="prog", data=df6, palette='viridis', legend=False)
plt.title('Expected Number of Awards vs Math Score by Program Type')
plt.xlabel('Math Score')
plt.ylabel('Number of Awards')
plt.show()

"""---

### **Problem 7**

**Problem Statement:**
School administrators study the attendance behavior of high school juniors at two schools. Predictors of the number of days of absence include the type of program in which the student is enrolled and a standardized test in math. The data set is taken from `[https://stats.idre.ucla.edu/stat/stata/dae/nb_data.dta](https://stats.idre.ucla.edu/stat/stata/dae/nb_data.dta)` and fit the negative binomial generalized linear models (GLMs) to identify the factors associated with number of days of absence. Interpret the result.

**Python Code:**
"""

import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

# 1. Read Stata File
url7 = "https://stats.idre.ucla.edu/stat/stata/dae/nb_data.dta"
df7 = pd.read_stata(url7)

# 2. Fit Negative Binomial GLM
# Using smf.glm with the NegativeBinomial family
model7 = smf.glm("daysabs ~ math + C(prog)", data=df7,
                 family=sm.families.NegativeBinomial()).fit()
print(model7.summary())

"""---

### **Problem 8**

**Problem Statement:**
The state wildlife biologists want to model how many fish are being caught by fishermen at a state park. Visitors are asked how long they stayed, how many people were in the group, were there children in the group and how many fish were caught. Some visitors do not fish, but there is no data on whether a person fished or not. Some visitors who did fish did not catch any fish so there are excess zeros in the data because of the people that did not fish. The data set is taken from `[https://stats.idre.ucla.edu/stat/data/fish.csv](https://stats.idre.ucla.edu/stat/data/fish.csv)` and fit the Zero-Inflated Poisson regression generalized linear models (GLMs) to identify the factors associated with number of fish caught. Interpret the result.

**Python Code:**
"""

import pandas as pd
import statsmodels.api as sm
from statsmodels.discrete.count_model import ZeroInflatedPoisson

# 1. Read Data
url8 = "https://stats.idre.ucla.edu/stat/data/fish.csv"
df8 = pd.read_csv(url8)

# 2. Define target and predictors
endog = df8['count']
# Count model predictors
exog = sm.add_constant(df8[['camper', 'persons', 'child']])
# Zero-inflation logistic model predictors
exog_infl = sm.add_constant(df8[['persons']])

# 3. Fit Zero-Inflated Poisson (ZIP)
zip_model = ZeroInflatedPoisson(endog, exog, exog_infl=exog_infl, inflation='logit').fit(maxiter=100)
print("=== Zero-Inflated Poisson (ZIP) Model ===")
print(zip_model.summary())

"""---

### **Problem 9**

**Problem Statement:**
The state wildlife biologists want to model how many fish are being caught by fishermen at a state park. Visitors are asked how long they stayed, how many people were in the group, were there children in the group and how many fish were caught. Some visitors do not fish, but there is no data on whether a person fished or not. Some visitors who did fish did not catch any fish so there are excess zeros in the data because of the people that did not fish. The data set is taken from `[https://stats.idre.ucla.edu/stat/data/fish.csv](https://stats.idre.ucla.edu/stat/data/fish.csv)` and fit the Zero-Inflated Negative Binomial regression generalized linear models (GLMs) to identify the factors associated with number of fish caught. Interpret the result.

**Python Code:**
"""

import pandas as pd
import statsmodels.api as sm
from statsmodels.discrete.count_model import ZeroInflatedNegativeBinomialP

# 1. Read Data
url9 = "https://stats.idre.ucla.edu/stat/data/fish.csv"
df9 = pd.read_csv(url9)

# 2. Define target and predictors
endog = df9['count']
exog = sm.add_constant(df9[['camper', 'persons', 'child']])
exog_infl = sm.add_constant(df9[['persons']])

# 3. Fit Zero-Inflated Negative Binomial (ZINB)
zinb_model = ZeroInflatedNegativeBinomialP(endog, exog, exog_infl=exog_infl, inflation='logit').fit(maxiter=100)
print("=== Zero-Inflated Negative Binomial (ZINB) Model ===")
print(zinb_model.summary())

"""---

### **Problem 10**

**Problem Statement:**
A study of length of hospital stay, in days, as a function of age, kind of health insurance and whether or not the patient died while in the hospital. Length of hospital stay is recorded as a minimum of at least one day. The data set is taken from `[https://stats.idre.ucla.edu/stat/data/ztp.dta](https://stats.idre.ucla.edu/stat/data/ztp.dta)` and fit the zero-truncated Poisson regression generalized linear models (GLMs) to identify the factors associated with length of hospital stay. Interpret the result.

**Python Code:**
"""

import pandas as pd
!pip install pyreadstat
import pyreadstat
import requests

# URL of the Stata file
url = "https://stats.idre.ucla.edu/stat/data/ztp.dta"
filename = "ztp.dta"

# Download the file
response = requests.get(url)
with open(filename, 'wb') as f:
    f.write(response.content)

# Use pyreadstat to read the Stata file (supports older/newer versions better than pandas default)
try:
    df_converted, meta = pyreadstat.read_dta(filename)

    # Save to CSV
    csv_filename = "ztp.csv"
    df_converted.to_csv(csv_filename, index=False)

    print(f"Successfully converted {filename} to {csv_filename}")
    display(df_converted.head())
except Exception as e:
    print(f"An error occurred: {e}")

import pandas as pd
import statsmodels.api as sm
# In newer versions of statsmodels, these are located in statsmodels.discrete.truncated_model
from statsmodels.discrete.truncated_model import TruncatedLFPoisson

# 1. Read Data
df10 = pd.read_csv('ztp.csv')

# 2. Define variables
endog_zt = df10['stay']
exog_zt = sm.add_constant(df10[['age', 'hmo', 'died']])

# 3. Fit Zero-Truncated Poisson Model
ztp_model = TruncatedLFPoisson(endog_zt, exog_zt).fit(disp=False)
print("=== Zero-Truncated Poisson Model ===")
print(ztp_model.summary())

"""---

### **Problem 11**

**Problem Statement:**
A study of length of hospital stay, in days, as a function of age, kind of health insurance and whether or not the patient died while in the hospital. Length of hospital stay is recorded as a minimum of at least one day. The data set is taken from `[https://stats.idre.ucla.edu/stat/data/ztp.dta](https://stats.idre.ucla.edu/stat/data/ztp.dta)` and fit the zero-truncated negative binomial regression generalized linear models (GLMs) to identify the factors associated with length of hospital stay. Interpret the result.

**Python Code:**
"""

import pandas as pd
import statsmodels.api as sm
from statsmodels.discrete.truncated_model import TruncatedLFNegativeBinomialP

# 1. Read Data
df11 = pd.read_csv('ztp.csv')

# 2. Define variables
endog_zt = df11['stay']
exog_zt = sm.add_constant(df11[['age', 'hmo', 'died']])

# 3. Fit Zero-Truncated Negative Binomial Model
ztnb_model = TruncatedLFNegativeBinomialP(endog_zt, exog_zt).fit(disp=False)
print("=== Zero-Truncated Negative Binomial Model ===")
print(ztnb_model.summary())